# Generated by Django 4.1.2 on 2022-11-02 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('P', 'Physical'), ('F', 'Financial'), ('E', 'Education'), ('M', 'Mental'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('progress_comment', models.TextField(max_length=250)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.goal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='rewards',
            field=models.ManyToManyField(to='main_app.reward'),
        ),
    ]
