# Generated by Django 4.1.2 on 2022-10-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_goal_category_updating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('P', 'Physical'), ('F', 'Financial'), ('E', 'Education'), ('M', 'Mental'), ('O', 'Other')], default='O', max_length=100),
        ),
    ]
