# Generated by Django 4.1.2 on 2022-11-02 05:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_reward_alter_goal_category_update_goal_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completed_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={'Complete'}),
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=model_utils.fields.StatusField(choices=[('In Progress', 'In Progress'), ('Complete', 'Complete')], default='In Progress', max_length=100, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='update',
            name='complete_status',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='complete_status', to='main_app.goal', verbose_name='Goal Complete?'),
        ),
    ]
