# Generated by Django 4.1.2 on 2022-11-02 08:36

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_goal_completed_at_goal_status_update_complete_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='update',
            name='complete_status',
        ),
        migrations.AddField(
            model_name='update',
            name='status',
            field=model_utils.fields.StatusField(choices=[('In Progress', 'In Progress'), ('Complete', 'Complete')], default='In Progress', max_length=100, no_check_for_status=True),
        ),
    ]
