# Generated by Django 4.1.2 on 2022-10-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_goal_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Updating',
            new_name='Update',
        ),
    ]
