# Generated by Django 4.1.2 on 2022-10-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_updating_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('P', 'Physical'), ('F', 'Financial'), ('E', 'Education'), ('M', 'Mental'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='goal',
            name='rewards',
            field=models.ManyToManyField(to='main_app.reward'),
        ),
    ]
