# Generated by Django 4.1.2 on 2022-11-04 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_goal_goal_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='goal_week',
        ),
    ]
