# Generated by Django 4.1.2 on 2022-10-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_goal_complete_status_update_complete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='complete_status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Goal Complete?'),
        ),
    ]
