# Generated by Django 4.1.2 on 2022-10-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_update_complete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='complete_status',
            field=models.BooleanField(verbose_name='Goal Complete?'),
        ),
    ]
